### ISSUE TITLE
Dúvidas 2018

### ISSUE THREAD

**Issue by PauloBoaventura** [wagoid/busca-cep#5]
Este código esta funcionando em PHP 5, 5.6, 7.0, 7.1 ou até mesmo em 7.2 ?
São muitas dúvidas e nada pessoal... (Já deixo claro)
Este código esta nas normativas novas dos correios (2017) e que pelo visto já existe novas normativas em (2018)...
Bom, este não é o único que visualizamos que aparentemente esta tudo correto.
Mas, tenho que ser este USUÁRIO questionador, já que estamos enfrentando tantos problemas seja eles em PHP, AJAX ou qualquer impulso anterior á 2017.
E assim vem as dúvidas...

Gostaria de saber se podemos implementar este código em outras ferramentas e até mesmo em outas plataformas... 

Espero que tenhamos uma resposta satisfatória e um UPGRADE. (O que neste notamos que o upgrade é notavel).

**Comment by wagoid** [comment]
@PauloBoaventura Olá. Infelizmente não possuo respostas para as suas perguntas. Esta biblioteca é escrita em Node.js, e ela faz uma requisição à API do ViaCEP, que por sua vez é um wrapper para o web service dos correios.

Caso você queira saber algo sobre a implementação do ViaCEP, você pode entrar em contato com o dono da API.Você irá encontrar seu email na página do ViaCEP: https://viacep.com.br

**Comment by PauloBoaventura** [comment]
Olá @wagoid 

Bom minha dúvida era se esta implementação estava funcionando atualmente... 
E o meu problema é colocar uma aplicação CEP na plataforma magento 1.9 ou 2.1, que funcione para calculo de frete e que insira o valor deste, no final do pedido.

Se souber algo... Por favor compartilhe!
Abs!

**Comment by wagoid** [comment]
@PauloBoaventura saquei. Ela ta funcionando tranquilo sim. Mas como é escrita em Node.js, não vai te ajudar muito. Depois da uma olhada no site do viacep, tem outras bibliotecas lá em PHP que usam a  API :)

Abraços!

**Comment by PauloBoaventura** [comment]
Olá @wagoid 
Obrigado pela ajuda!!!
Vou testar e posto novidades!!!
Abs
