### ISSUE TITLE
Erros ao tentar utilizar o busca-cep

### ISSUE THREAD

**Issue by filipedesousab** [wagoid/busca-cep#8]
Bom dia.
Está ocorrendo um erro ao tentar importar a dependência com `import buscaCep from 'busca-cep';` ou com `const buscaCep = require('busca-cep');`.
Estou utilizando webpack;

O erro na saída:

`ERROR in ./node_modules/request-promise/lib/rp.js
Module not found: Error: Can't resolve 'cls-bluebird' in '/local/dos/arquivos/node_modules/request-promise/lib'
 @ ./node_modules/request-promise/lib/rp.js 153:4-27
 @ ./node_modules/busca-cep/index.js
 @ ./src/components/FormToRegisterAndUpdateEmployee.jsx
 @ ./src/components/ScreenToRegisterEmployee.jsx
 @ ./src/containers/ScreenToRegisterEmployee.js
 @ ./src/components/RegistrationScreenCaller.jsx
 @ ./src/EmployeesComponent.jsx
 @ ./src/EmployeesContainer.js
 @ ./src/PersonnelDepartment/index.js
 @ ./src/routes.jsx
 @ ./src/App.jsx
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://0.0.0.0:3000 (webpack)/hot/dev-server.js ./src/index.jsx ./src/common/scss/dependencies.scss ./src/common/scss/custom.scss

ERROR in ./node_modules/request/lib/har.js
Module not found: Error: Can't resolve 'fs' in '/local/dos/arquivos/node_modules/request/lib'
 @ ./node_modules/request/lib/har.js 3:9-22
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/request-promise/lib/rp.js
 @ ./node_modules/busca-cep/index.js
 @ ./src/components/FormToRegisterAndUpdateEmployee.jsx
 @ ./src/components/ScreenToRegisterEmployee.jsx
 @ ./src/containers/ScreenToRegisterEmployee.js
 @ ./src/components/RegistrationScreenCaller.jsx
 @ ./src/EmployeesComponent.jsx
 @ ./src/EmployeesContainer.js
 @ ./src/PersonnelDepartment/index.js
 @ ./src/routes.jsx
 @ ./src/App.jsx
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://0.0.0.0:3000 (webpack)/hot/dev-server.js ./src/index.jsx ./src/common/scss/dependencies.scss ./src/common/scss/custom.scss

ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'net' in '/local/dos/arquivos/node_modules/forever-agent'
 @ ./node_modules/forever-agent/index.js 6:10-24
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/request-promise/lib/rp.js
 @ ./node_modules/busca-cep/index.js
 @ ./src/components/FormToRegisterAndUpdateEmployee.jsx
 @ ./src/components/ScreenToRegisterEmployee.jsx
 @ ./src/containers/ScreenToRegisterEmployee.js
 @ ./src/components/RegistrationScreenCaller.jsx
 @ ./src/EmployeesComponent.jsx
 @ ./src/EmployeesContainer.js
 @ ./src/PersonnelDepartment/index.js
 @ ./src/routes.jsx
 @ ./src/App.jsx
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://0.0.0.0:3000 (webpack)/hot/dev-server.js ./src/index.jsx ./src/common/scss/dependencies.scss ./src/common/scss/custom.scss

ERROR in ./node_modules/tough-cookie/lib/cookie.js
Module not found: Error: Can't resolve 'net' in '/local/dos/arquivos/node_modules/tough-cookie/lib'
 @ ./node_modules/tough-cookie/lib/cookie.js 32:10-24
 @ ./node_modules/request/lib/cookies.js
 @ ./node_modules/request/index.js
 @ ./node_modules/request-promise/lib/rp.js
 @ ./node_modules/busca-cep/index.js
 @ ./src/components/FormToRegisterAndUpdateEmployee.jsx
 @ ./src/components/ScreenToRegisterEmployee.jsx
 @ ./src/containers/ScreenToRegisterEmployee.js
 @ ./src/components/RegistrationScreenCaller.jsx
 @ ./src/EmployeesComponent.jsx
 @ ./src/EmployeesContainer.js
 @ ./src/PersonnelDepartment/index.js
 @ ./src/routes.jsx
 @ ./src/App.jsx
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://0.0.0.0:3000 (webpack)/hot/dev-server.js ./src/index.jsx ./src/common/scss/dependencies.scss ./src/common/scss/custom.scss

ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'net' in '/local/dos/arquivos/node_modules/tunnel-agent'
 @ ./node_modules/tunnel-agent/index.js 3:10-24
 @ ./node_modules/request/lib/tunnel.js
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/request-promise/lib/rp.js
 @ ./node_modules/busca-cep/index.js
 @ ./src/components/FormToRegisterAndUpdateEmployee.jsx
 @ ./src/components/ScreenToRegisterEmployee.jsx
 @ ./src/containers/ScreenToRegisterEmployee.js
 @ ./src/components/RegistrationScreenCaller.jsx
 @ ./src/EmployeesComponent.jsx
 @ ./src/EmployeesContainer.js
 @ ./src/PersonnelDepartment/index.js
 @ ./src/routes.jsx
 @ ./src/App.jsx
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://0.0.0.0:3000 (webpack)/hot/dev-server.js ./src/index.jsx ./src/common/scss/dependencies.scss ./src/common/scss/custom.scss

ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'tls' in '/local/dos/arquivos/node_modules/forever-agent'
 @ ./node_modules/forever-agent/index.js 7:10-24
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/request-promise/lib/rp.js
 @ ./node_modules/busca-cep/index.js
 @ ./src/components/FormToRegisterAndUpdateEmployee.jsx
 @ ./src/components/ScreenToRegisterEmployee.jsx
 @ ./src/containers/ScreenToRegisterEmployee.js
 @ ./src/components/RegistrationScreenCaller.jsx
 @ ./src/EmployeesComponent.jsx
 @ ./src/EmployeesContainer.js
 @ ./src/PersonnelDepartment/index.js
 @ ./src/routes.jsx
 @ ./src/App.jsx
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://0.0.0.0:3000 (webpack)/hot/dev-server.js ./src/index.jsx ./src/common/scss/dependencies.scss ./src/common/scss/custom.scss

ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'tls' in '/local/dos/arquivos/node_modules/tunnel-agent'
 @ ./node_modules/tunnel-agent/index.js 4:10-24
 @ ./node_modules/request/lib/tunnel.js
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/request-promise/lib/rp.js
 @ ./node_modules/busca-cep/index.js
 @ ./src/components/FormToRegisterAndUpdateEmployee.jsx
 @ ./src/components/ScreenToRegisterEmployee.jsx
 @ ./src/containers/ScreenToRegisterEmployee.js
 @ ./src/components/RegistrationScreenCaller.jsx
 @ ./src/EmployeesComponent.jsx
 @ ./src/EmployeesContainer.js
 @ ./src/PersonnelDepartment/index.js
 @ ./src/routes.jsx
 @ ./src/App.jsx
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://0.0.0.0:3000 (webpack)/hot/dev-server.js ./src/index.jsx ./src/common/scss/dependencies.scss ./src/common/scss/custom.scss`

**Comment by wagoid** [comment]
Olá @filipedesousab! É possível que seja algum problema na sua configuração do Webpack. Poderia compartilhar um projeto com o código mínimo para reproduzir o erro?

**Comment by filipedesousab** [comment]
Sim, vou organizar um e coloco aqui.

**Comment by wagoid** [comment]
Issue abandonada, fechando.
